services:
  - type: web
    name: maman-magique-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free
    buildFilter:
      paths:
        - "*"
    autoDeploy: true
    build:
      clearCache: true
